
CONFIG_USB_DFU_CLASS=y
CONFIG_USB_DFU_REBOOT=y
CONFIG_USB_DEVICE_STACK=y
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_STREAM_FLASH=y
CONFIG_IMG_MANAGER=y
CONFIG_FLASH_PAGE_LAYOUT=y

CONFIG_SINGLE_APPLICATION_SLOT=y

CONFIG_BOOT_SIGNATURE_TYPE_ECDSA_P256=y
CONFIG_HUB_PORTS=n
CONFIG_BOOT_MAX_IMG_SECTORS=64
CONFIG_MAIN_STACK_SIZE=4096

CONFIG_BOOT_USB_DFU_GPIO=y
CONFIG_BOOT_USB_DFU_NO_APPLICATION=y

CONFIG_BOOT_BANNER_STRING="MCUboot with Zephyr build"

CONFIG_USB_DFU_PERMANENT_DOWNLOAD=y
CONFIG_USB_DEVICE_LOG_LEVEL_DBG=y
