# Copyright (c) 2024 Fabian Pflug
# SPDX-License-Identifier: Apache-2.0

manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: gumulka
      url-base: https://github.com/gumulka

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: v3.6.0
      import:
        name-allowlist:
          - cmsis
          - hal_stm32
          - segger
    - name: mcuboot
      remote: gumulka
      revision: 859688998261c16e2be230a7d0f400de56811160
      path: bootloader/mcuboot
