# Copyright (c) 2024 Fabian Pflug
# SPDX-License-Identifier: Apache-2.0

# compiler
CONFIG_DEBUG_OPTIMIZATIONS=y

CONFIG_LOG=y
CONFIG_CONSOLE=y
CONFIG_RTT_CONSOLE=y
CONFIG_USE_SEGGER_RTT=y
CONFIG_LOG_BACKEND_RTT=y
